protected/modules/assessment/controllers/HistoryController.php
<?php
/**
 * HistoryController
 * @var $this HistoryController
 * @var $model AssessmentCareerTests
 * @var $form CActiveForm
 *
 * Reference start
 * TOC :
 *	Index
 *	Manage
 *	View
 *
 *	LoadModel
 *	performAjaxValidation
 *
 * @author Putra Sudaryanto <putra@sudaryanto.id>
 * @contact (+62)856-299-4114
 * @copyright Copyright (c) 2018 Ommu Platform (www.ommu.co)
 * @created date 29 July 2018, 18:24 WIB
 * @modified date 29 July 2018, 18:24 WIB
 * @link https://bitbucket.org/ommu/ps-career-interest
 *
 *----------------------------------------------------------------------------------------------------------
 */

class HistoryController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	//public $layout='//layouts/column2';
	public $defaultAction = 'index';

	/**
	 * Initialize admin page theme
	 */
	public function init() 
	{
		$arrThemes = $this->currentTemplate('public');
		Yii::app()->theme = $arrThemes['folder'];
		$this->layout = 'admin_default';
		$this->applyViewPath(__dir__); 
	}

	/**
	 * @return array action filters
	 */
	public function filters() 
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules() 
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','manage','view'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->level',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex() 
	{
		$this->redirect(array('manage'));
	}

	/**
	 * Manages all models.
	 */
	public function actionManage() 
	{
		$model=new AssessmentCareerTests('search');
		$model->unsetAttributes();	// clear any default values
		$AssessmentCareerTests = Yii::app()->getRequest()->getParam('AssessmentCareerTests');

		$AssessmentCareerTests['user_id']=Yii::app()->user->id;
		if($AssessmentCareerTests)
			$model->attributes=$AssessmentCareerTests;

		$this->pageTitle = Yii::t('phrase', 'Histories');
		$this->pageDescription = '';
		$this->pageMeta = '';
		$this->render('front_manage', array(
			'model'=>$model,
		));
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id) 
	{
		$model=$this->loadModel($id);

		$this->pageTitle = Yii::t('phrase', 'Detail Career Test: {user_id}', array('{user_id}'=>$model->user->displayname));
		$this->pageDescription = '';
		$this->pageMeta = '';
		$this->render('front_view', array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id) 
	{
		$model = AssessmentCareerTests::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404, Yii::t('phrase', 'The requested page does not exist.'));
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model) 
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='assessment-career-tests-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}

protected/modules/assessment/controllers/MemberController.php
<?php
/**
 * MemberController
 * @var $this MemberController
 *
 * Reference start
 * TOC :
 *	Index
 *
 * @author Putra Sudaryanto <putra@sudaryanto.id>
 * @contact (+62)856-299-4114
 * @copyright Copyright (c) 2018 Ommu Platform (www.ommu.co)
 * @created date 31 July 2018, 19:27 WIB
 * @link https://bitbucket.org/ommu/ps-career-interest
 *
 *----------------------------------------------------------------------------------------------------------
 */

class MemberController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	//public $layout='//layouts/column2';
	public $defaultAction = 'index';

	/**
	 * Initialize admin page theme
	 */
	public function init() 
	{
		$arrThemes = $this->currentTemplate('public');
		Yii::app()->theme = $arrThemes['folder'];
		$this->layout = $arrThemes['layout'];
		$this->applyViewPath(__dir__); 
	}

	/**
	 * @return array action filters
	 */
	public function filters() 
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules() 
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->level',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex() 
	{
		$user_id = Yii::app()->user->id;
		$setting = AssessmentCareerSetting::model()->findByPk(1);
		$userInterestTest = AssessmentCareerUsers::model()->findByAttributes(array(
			'user_id'=>$user_id,
		));
		$interestTestID = $userInterestTest ? $userInterestTest->view->last_test_id : 0;

		$interestTestCondition = false;
		$interestTestWait = false;
		if($userInterestTest->view->testView->active == 1)
			$interestTestCondition = true;
		else {
			if($userInterestTest->view->testView->waiting == 1) {
				$interestTestCondition = true;
				$interestTestWait = true;
			}
		}
		$interestTest = array(
			'id'=>$interestTestID,
			'running'=>$interestTestCondition,
			'waiting'=>$interestTestWait,
			'start_date'=>$interestTestID ? $userInterestTest->view->test->start_date : '',
			'next_test_date'=>$interestTestWait ? $userInterestTest->view->test->next_test_date : '',
		);

		$this->pageTitle = Yii::t('phrase', 'Personal Assessments');
		$this->pageDescription = '';
		$this->pageMeta = '';
		$this->render('front_index', array(
			'setting'=>$setting,
			'interestTest'=>$interestTest,
		));
	}

}

protected/modules/assessment/views/careerTest/front_agreement.php
<?php
/**
 * Assessment Career Tests (assessment-career-tests)
 * @var $this TestController
 * @var $model AssessmentCareerTests
 *
 * @author Putra Sudaryanto <putra@sudaryanto.id>
 * @contact (+62)856-299-4114
 * @copyright Copyright (c) 2018 Ommu Platform (www.ommu.co)
 * @created date 29 July 2018, 18:24 WIB
 * @modified date 29 July 2018, 18:24 WIB
 * @link https://bitbucket.org/ommu/ps-career-interest
 *
 */

	$this->breadcrumbs=array(
		'Assessments'=>Yii::app()->controller->createUrl('member/index'),
		'Career'=>Yii::app()->controller->createUrl('index'),
	);
?>

<?php echo $this->parseTemplate($setting->message_alert['agreement'], array(
	'start_url'=>Yii::app()->controller->createUrl('quiz'),
	'cancel_url'=>Yii::app()->createUrl('site/index'),
));?>

protected/modules/assessment/views/careerTest/front_index.php
<?php
/**
 * Assessment Career Tests (assessment-career-tests)
 * @var $this TestController
 * @var $model AssessmentCareerTests
 *
 * @author Putra Sudaryanto <putra@sudaryanto.id>
 * @contact (+62)856-299-4114
 * @copyright Copyright (c) 2018 Ommu Platform (www.ommu.co)
 * @created date 29 July 2018, 18:24 WIB
 * @modified date 29 July 2018, 18:24 WIB
 * @link https://bitbucket.org/ommu/ps-career-interest
 *
 */

	$this->breadcrumbs=array(
		'Assessments'=>Yii::app()->controller->createUrl('member/index'),
		'Career'=>Yii::app()->controller->createUrl('index'),
	);

	$message_alert_alert_new = $this->parseTemplate($setting->message_alert['alert']['new'], array(
		'period_test_difference'=>$setting->period_test_difference,
		'period_test_diff_type'=>AssessmentCareerSetting::getPeriodTestDiffType($setting->period_test_diff_type),
	));
	$message_alert_alert_new = preg_replace("/[\\n\\r]+/", "", $message_alert_alert_new);
	$agreement_url = Yii::app()->controller->createUrl('agree');

	$message_alert_alert_running = $this->parseTemplate($setting->message_alert['alert']['running'], array(
		'period_test_difference'=>$setting->period_test_difference,
		'period_test_diff_type'=>AssessmentCareerSetting::getPeriodTestDiffType($setting->period_test_diff_type),
	));
	$message_alert_alert_running = preg_replace("/[\\n\\r]+/", "", $message_alert_alert_running);
	$quiz_url = Yii::app()->controller->createUrl('quiz');

	$testCondition = $testCondition == true ? 1 : 0;

	$cs = Yii::app()->getClientScript();
	$cs->registerCssFile(Yii::app()->theme->baseUrl.'/plugins/sweetalert/sweetalert.css');
	$cs->registerScriptFile(Yii::app()->theme->baseUrl.'/plugins/sweetalert/sweetalert.min.js', CClientScript::POS_END);
$js=<<<EOP
	var testCondition = $testCondition;
	$(function () {
		$('button#js-sweetalert').on('click', function () {
			var type = $(this).data('type');
			if (type === 'to-alert') {
				showAlertMessage();
			}
		});
	});
	function showAlertMessage() {
		if(testCondition == 0) {
			swal({
				title: 'Are you sure?',
				text: '$message_alert_alert_new',
				showCancelButton: true,
				confirmButtonText: 'Lanjut',
				closeOnConfirm: false,
				html: true
			}, function () {
				location.href = '$agreement_url';
			});
		} else {
			swal({
				title: 'Are you sure???',
				text: '$message_alert_alert_running',
				showCancelButton: true,
				confirmButtonText: 'Lanjut',
				closeOnConfirm: false,
				html: true
			}, function () {
				location.href = '$quiz_url';
			});
		}
	}
EOP;
	$cs->registerScript('dialog-alert', $js, CClientScript::POS_END);
?>

<div class="card">
	<?php echo $this->parseTemplate($setting->message_alert['attention']);?>

	<div class="row">
		<div class="col-lg-3 col-md-4 col-sm-12">
		</div>
		<div class="col-lg-9 col-md-8 col-sm-12">
			<div class="body">
				<button id="js-sweetalert" class="btn btn-raised btn-primary waves-effect" data-type="to-alert">Lanjut</button>
				<a class="btn btn-raised bg-blue-grey waves-effect" href="<?php echo Yii::app()->controller->createUrl('member/index');?>" title="Batal">Batal</a>
			</div>
		</div>
	</div>
</div>

protected/modules/assessment/views/careerTest/front_quiz.php
<?php
/**
 * Assessment Career Tests (assessment-career-tests)
 * @var $this TestController
 * @var $model AssessmentCareerTests
 *
 * @author Putra Sudaryanto <putra@sudaryanto.id>
 * @contact (+62)856-299-4114
 * @copyright Copyright (c) 2018 Ommu Platform (www.ommu.co)
 * @created date 29 July 2018, 18:24 WIB
 * @modified date 29 July 2018, 18:24 WIB
 * @link https://bitbucket.org/ommu/ps-career-interest
 *
 */

	$this->breadcrumbs=array(
		'Assessments'=>Yii::app()->controller->createUrl('member/index'),
		'Career'=>Yii::app()->controller->createUrl('index'),
	);

	$message_instruction = $this->parseTemplate($setting->message_alert['instruction'], array(
		'period_test_difference'=>$setting->period_test_difference,
		'period_test_diff_type'=>AssessmentCareerSetting::getPeriodTestDiffType($setting->period_test_diff_type),
	));
	$message_instruction = preg_replace('/\s\s+/', '', $message_instruction);
	$test_url = Yii::app()->controller->createUrl('quiz');
	$index_url = Yii::app()->createUrl('site/index');

	$testCondition = $testCondition == true ? 1 : 0;
	$stepMax = $statementGroup->group_total_i;
	$stepFrom = ($stepMax - $statementGroupCount) + 1;

	$cs = Yii::app()->getClientScript();
	$cs->registerCssFile(Yii::app()->theme->baseUrl.'/plugins/sweetalert/sweetalert.css');
	$cs->registerScriptFile(Yii::app()->theme->baseUrl.'/plugins/sweetalert/sweetalert.min.js', CClientScript::POS_END);
	$cs->registerCssFile(Yii::app()->theme->baseUrl.'/plugins/ion-rangeslider/css/ion.rangeSlider.css');
	$cs->registerCssFile(Yii::app()->theme->baseUrl.'/plugins/ion-rangeslider/css/ion.rangeSlider.skinFlat.css');
	$cs->registerScriptFile(Yii::app()->theme->baseUrl.'/plugins/ion-rangeslider/js/ion-rangeSlider/ion.rangeSlider.js', CClientScript::POS_END);
$js=<<<EOP
	var testCondition = $testCondition;
	var testUrl = location.href;
	var form = $('#assessment-career-test');
	var formAction = form.attr('action');

	var stepMax = $stepMax;
	var stepFrom = $stepFrom;

	$(function () {
		$('.js-sweetalert button').on('click', function() {
			var type = $(this).data('type');
			if (type === 'to-instruction') {
				showAlertMessage();
			}
		});
	});
	function showAlertMessage() {
		swal({
			title: 'Instruction',
			text: '$message_instruction',
			showCancelButton: true,
			confirmButtonText: 'Lanjut',
			closeOnConfirm: false,
			html: true
		}, function () {
			location.href = '$test_url';
		});
	}
	if(testCondition == 0) {
		runTest();
		$('#defaultModal').on('show.bs.modal', function (event) {
			var modal = $(this);
			modal.find('.modal-title').text('Instruksi');
			modal.find('.modal-body').html('$message_instruction');
			modal.find('#modalSubmit').text('Mulai');
			modal.find('#modalCancel').text('Batal');
		});
		$('#defaultModal').modal('show');
	
		$('#modalSubmit').on('click', function() {
			$.ajax({
				method: 'POST',
				url: testUrl,
				data: {start: 'true'},
				success: function(response) {
					location.reload();
				},
				error: function(jqXHR, textStatus, error) {
					location.href = testUrl;
				}
			});
		});
	
		$('#modalCancel').on('click', function() {
			location.href = '$index_url';
		});
	} else {
		runTest();
		form.find('input').on('change', function() {
			$.ajax({
				method: 'POST',
				url: testUrl,
				data: form.serialize(),
				dataType: 'json',
				success: function(response) {
					var hasError = 0;
					if(countProperties(response) > 0) {
						for(i in response) {
							if(i.indexOf('_'))
								hasError = 1;
						}
						if(hasError == 1) {
							$('form[action="'+formAction+'"]').find('div.errorMessage').hide().html('');
							for(i in response) {
								$('form[action="'+formAction+'"] #' + i + '_em_').show().html(response[i][0]);
							}
						}
					} else
						location.reload();
				},
				error: function(jqXHR, textStatus, error) {
					location.href = testUrl;
				}
			});
		});
	}
	
	function countProperties(obj) {
		var prop;
		var propCount = 0;
	
		for (prop in obj) {
			propCount++;
		}
		return propCount;
	}
	
	function runTest() {
		$('#range_01').ionRangeSlider({
			min: 0,
			max: stepMax,
			from: stepFrom
		});
	}
EOP;
	$cs->registerScript('dialog-alert', $js, CClientScript::POS_END);
?>

<div class="card">
	<div class="row clearfix">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="header">
				<input id="range_01"/>
			</div>
		</div>
	</div>
</div>

<?php
$statements = $statementGroup->statements;
$statement_choice = AssessmentCareerTestDetail::getStatementChoice();
if(!$testCondition || !empty($statements)) {
	$model=new AssessmentCareerTestDetail;

	$form=$this->beginWidget('application.libraries.yii-traits.system.OActiveForm', array(
		'id'=>'assessment-career-test',
		'enableAjaxValidation'=>true,
		/*
		'htmlOptions' => array(
			'enctype' => 'multipart/form-data',
			'on_post' => '',
		),
		'enableClientValidation'=>true,
		'clientOptions'=>array(
			'validateOnSubmit'=>true,
		),
		*/
	));?>
<div class="card question">
	<div class="row clearfix">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="header">
				<div class="progress">
					<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"> <span class="sr-only">60% Complete</span> </div>
				</div>
			</div>
		</div>
	</div>
	<?php /*
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12">
		</div>
		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="body">
				<div class="row">
				<?php foreach($statement_choice as $key => $val) {?>
					<div class="col-lg-2 col-md-3 col-sm-3 align-center">
						<?php echo preg_replace('/ /', "<br/>", $val).'<br/>';?>
					</div>
				<?php }?>
				</div>
			</div>
		</div>
	</div>
	*/?>
	<?php 
	$statements = (array)$statements;
	shuffle($statements);
	foreach($statements as $key => $val) {?>
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="body">
				<h5><?php echo $val->statement->message;?></h5>
				<?php echo $form->error($model, 'statement_id_i['.$val->statement_id.']'); ?>
			</div>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="body">
				<?php echo $form->radioButtonList($model, 'statement_id_i['.$val->statement_id.']', $statement_choice);?>
			</div>
		</div>
	</div>
	<?php }?>
</div>
<?php $this->endWidget();
} else {?>
	aaaaa
<?php }?>

protected/modules/assessment/views/careerTest/front_result.php
<?php
/**
 * Assessment Career Tests (assessment-career-tests)
 * @var $this TestController
 * @var $model AssessmentCareerTests
 *
 * @author Putra Sudaryanto <putra@sudaryanto.id>
 * @contact (+62)856-299-4114
 * @copyright Copyright (c) 2018 Ommu Platform (www.ommu.co)
 * @created date 29 July 2018, 18:24 WIB
 * @modified date 31 July 2018, 09:19 WIB
 * @link https://bitbucket.org/ommu/ps-career-interest
 *
 */

	$this->breadcrumbs=array(
		'Assessments'=>Yii::app()->controller->createUrl('member/index'),
		'Career'=>Yii::app()->controller->createUrl('index'),
	);

	$result = array(
		array(
			'label'=>$model->getAttributeLabel('result.score_executor'),
			'value'=>AssessmentCareerTestResult::getIndex($model->result->score_executor, true),
		),
		array(
			'label'=>$model->getAttributeLabel('result.score_thinker'),
			'value'=>AssessmentCareerTestResult::getIndex($model->result->score_thinker, true),
		),
		array(
			'label'=>$model->getAttributeLabel('result.score_creator'),
			'value'=>AssessmentCareerTestResult::getIndex($model->result->score_creator, true),
		),
		array(
			'label'=>$model->getAttributeLabel('result.score_savior'),
			'value'=>AssessmentCareerTestResult::getIndex($model->result->score_savior, true),
		),
		array(
			'label'=>$model->getAttributeLabel('result.score_persuader'),
			'value'=>AssessmentCareerTestResult::getIndex($model->result->score_persuader, true),
		),
		array(
			'label'=>$model->getAttributeLabel('result.score_organizer'),
			'value'=>AssessmentCareerTestResult::getIndex($model->result->score_organizer, true),
		)
	);
	$resultValue = CJSON::encode($result);
	$interestCount = count($interest);

	$cs = Yii::app()->getClientScript();
	$cs->registerScriptFile(Yii::app()->theme->baseUrl.'/js/sparkline.bundle.js', CClientScript::POS_END); 
	$cs->registerScriptFile(Yii::app()->theme->baseUrl.'/js/morrisscripts.bundle.js', CClientScript::POS_END);
$js=<<<EOP
	Morris.Donut({
		element: 'donut_chart',
		data: $resultValue,
		colors: ['rgb(0,189,209)', 'rgb(137,197,75)', 'rgb(27,138,207)', 'rgb(168,104,224)', 'rgb(255,200,0)', 'rgb(121,85,72)'],
		formatter: function (y) {
			return y
		}
	});
EOP;
	$cs->registerScript('dialog-alert', $js, CClientScript::POS_END);
?>

<div class="row clearfix">
	<div class="col-sm-12 col-md-6 col-lg-4">
		<div class="card">
			<div class="header">
				<h2><?php echo Yii::t('phrase', 'Grafik Minat');?></h2>
			</div>
			<div class="body">
				<div id="donut_chart" class="graph dashboard-donut-chart align-center"></div>
			</div>
		</div>
	</div>
	<div class="col-sm-12 col-md-6 col-lg-8">
		<div class="card">
			<div class="header">
				<h2><?php echo Yii::t('phrase', 'Diskripsi Minat');?></h2>
				<small><?php echo $interestCount>3 ? Yii::t('phrase', 'Kamu memiliki lebih dari 3 (tiga) minat dengan kategori tinggi') : ($interestCount==0 ? Yii::t('phrase', 'Kamu tidak memiliki minat dengan kategori tinggi') : Yii::t('phrase', 'Kamu memiliki '.$interestCount.' minat dengan kategori tinggi'));?></small>
			</div>
			<div class="body">
				<h3 class="align-center m-t-0 m-b-30"><code>"<?php echo $interestCount==0 ? Yii::t('phrase', 'Kamu Tidak Memiliki Minat') : ($interestCount==3 ? Yii::t('phrase', 'Kamu Memiliki Minat Spesifik') : Yii::t('phrase', 'Kamu Belum Memiliki Minat Spesifik'));?>"</code></h3>
				<?php echo $interestCount==0 ? Yii::t('phrase', 'Mohon maaf, hasil tes minat menunjukkan bahwa Saudara <strong>{displayname}</strong> belum memiliki peminatan yang spesifik.', array('{displayname}'=>$model->user->displayname)) : ($interestCount==3 ? Yii::t('phrase', '<p>Hasil tes minat menyebutkan bahwa Saudara <strong>{displayname}</strong> memiliki minat yang tinggi pada tipe <strong>{interest-type}</strong>. Urutan pertama menunjukkan adanya ketertarikan yang sangat tinggi dalam diri Saudara, diikuti oleh minat yang kedua dan minat yang ketiga.</p><p>Minat tersebut dapat diuraikan sebagai berikut:</p>', array('{displayname}'=>$model->user->displayname, '{interest-type}'=>implode(', ', AssessmentCareerTests::getInterestVariable($interest)))) : Yii::t('phrase', '<p>Hasil tes minat menyebutkan bahwa Saudara <strong>{displayname}</strong> memiliki minat yang tinggi pada tipe <strong>{interest-type}</strong>. Urutan pertama menunjukkan adanya ketertarikan yang sangat tinggi dalam diri Saudara, diikuti oleh minat-minat lainnya.</p><p>Minat tersebut dapat diuraikan sebagai berikut:</p>', array('{displayname}'=>$model->user->displayname, '{interest-type}'=>implode(', ', AssessmentCareerTests::getInterestVariable($interest)))));?>
			</div>
		</div>
	</div>
</div>

<?php if($interestCount!=0) {
	$criteria=new CDbCriteria;
	$criteria->select = 'variable_id, variable_name, interpretasi_desc';
	$criteria->compare('publish', 1);
	$variable = AssessmentCareerVariable::model()->findAll($criteria);?>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<div class="card">
			<div class="body">
				<!-- Nav tabs -->
				<ul class="nav nav-tabs">
					<?php 
					$i = 0;
					foreach($variable as $val) {
						if(!in_array($val->variable_id, $interest))
							continue;
						else
							$i++;?>
						<li class="nav-item"><a class="nav-link text-uppercase <?php echo $i == 1 ? 'active' : '';?>" data-toggle="tab" href="#<?php echo $this->urlTitle($val->title->message);?>" aria-expanded="true"><?php echo Yii::t('phrase', $val->title->message);?></a></li>
					<?php }?>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
					<?php 
					$i = 0;
					foreach($variable as $val) {
						if(!in_array($val->variable_id, $interest))
							continue;
						else
							$i++;?>
						<div role="tabpanel" class="tab-pane <?php echo $i == 1 ? 'in active' : '';?>" id="<?php echo $this->urlTitle($val->title->message);?>" aria-expanded="true">
							<?php echo $this->parseTemplate($val->interpretasi_desc, array(
								'displayname'=>$model->user->displayname,
							));?>
						</div>
					<?php }?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php }?>